ucladevx/Bmaps-Frontend

README.md, package-lock.json, package.json, public/css/styles.css, src/components/mainDisplay/mainDisplay.js, src/components/mainDisplay/sidebar/event.js, src/components/mainDisplay/sidebar/eventHeader.js, src/components/mainDisplay/sidebar/eventsList.js, src/index.js
Fixed BrowserRouter issues with links: moved BrowserRouter to root.
=> Tanzeela eventslist

public/js/main.js, views/index.hbs
Map icons, popups and zoom when clicking on icons
=> Hannah mapbox

public/js/main.js
=> changed json to backend

public/css/style.css, public/js/main.js, views/index.hbs
=> accessing events with updated backend

public/js/main.js
Parsed the times using a Date() object so that they show in the format `Dec 01 | 7 AM - 9 AM`
=> Tanzeela timeparsing

public/js/modal.js
=> updated date parsing on modals

Dockerfile, README.md, public/js/main.js, views/index.hbs
Frontend repo is embedded within a container in backend repo. Frontend doesn't need to do anything to get Docker working, other than having the Dockerfile.
Mappening-Backend
- nginx_app
- node_app = Mappening-Frontend
- python_app
=> Added working Dockerfile to frontend

public/js/utils.js
=> unenesting formatDate functions

README.md, public/js/main.js, views/index.hbs
=> Changed IP to AWS IP

public/css/style.css, public/js/main.js, views/index.hbs
categories header text changes with category (lowercase)
=> Tanzeela eventcategories

public/css/modal.css, public/css/style.css, public/js/modal.js, public/js/utils.js, views/index.hbs, views/partials/footer.hbs
1. updated modals
2. event image on left bar always square
=> Helen modals

public/js/utils.js, views/index.hbs
How can i better access the eventTemplate variables? And why is all this js in the html file?
=> Add the sidebar filter by date

public/js/map.js, public/js/utils.js
Changed map dates to milliseconds to avoid edge cases
=> Tanzeela fixnegativedates

public/css/style.css, public/js/main.js, views/partials/header.hbs
Search bar resizes with a lot of media queries... 
Should be redone later, but I couldn't figure out why percentage resizing wasn't working. I think it's okay for now?
=> Tanzeela mobilefriendly

public/css/style.css, public/js/filter.js, public/js/main.js, public/js/utils.js, views/partials/header.hbs
Some style stuff and category haha
=> Tanzeela unitesidebarandmap

public/css/style.css
=> slight mobile styling

Makefile, nginx/conf/nginx.conf, static/js/filter.js, static/js/main.js, static/js/utils.js
let -> var
global api url
less js caching
=> Small fixes

Makefile, static/css/style.css, static/js/utils.js, static/views/index.hbs, static/views/partials/footer.hbs
Not done bc I have to fix the search bar and consider how to do categories lol.
Sidebar is just closer to the mockup
=> Tanzeela redo sidebar

static/css/style.css, static/views/index.hbs
haven't done the cool animation for mobile friendly yet but it's up and coming
=> basic version of mobile friendly

src/app/map.service.ts, src/app/sidebar/sidebar.component.css, src/app/sidebar/sidebar.component.html, src/app/sidebar/sidebar.component.ts
sidebar connected to event service by date
=> sidebar connected to event service by date

nginx/conf/nginx.conf, static/js/utils.js
Production branch is a bit behind, missing HTTPS url
=> Move prod to HTTPS

src/app/date-selector/date-selector.component.css, src/app/date-selector/date-selector.component.html, src/app/date-selector/date-selector.component.ts, src/app/event.service.ts, src/app/selectedDate.ts
Looks ugly and doesn't have a date cap, but works. working on styling and stuff now
=> Date selector functionality

src/app/app.component.css, src/app/map-box/map-box.component.css, src/app/sidebar/sidebar.component.css, src/styles.css
=> may have fixed some scrolling

src/app/event-detail/event-detail.component.ts, src/app/map-box/map-box.component.ts, src/app/sidebar/sidebar.component.html, src/app/sidebar/sidebar.component.ts
Hover on map icon or sidebar:
Popup
Scroll
Darken
Click on map icon or sidebar:
Event Detail
Zoom
Popup
=> Tanzeela separate hover click

package.json, src/app/app.component.css, src/app/app.component.html, src/app/date-selector/date-selector.component.ts, src/app/event-detail/event-detail.component.css, src/app/event-detail/event-detail.component.html, src/app/event-detail/event-detail.component.ts, src/app/event.service.ts, src/app/map-box/map-box.component.css, src/app/map-box/map-box.component.ts, src/app/shared/date.service.ts, src/app/sidebar/sidebar.component.css, src/app/sidebar/sidebar.component.html, src/styles.css
- Fix 0AM bug
- Date/time formatting
- Event detail styles
=> Richard date

src/app/map-box/map-box.component.ts
=> hover from sidebar to make blue pin

README.md
=> updated yarn in readme

src/app/map-box/map-box.component.css, src/app/map-box/map-box.component.ts, src/app/navbar/navbar.component.css, src/app/navbar/navbar.component.html
A home button was added to the map box controls. When clicked, it will reset the map view to default zoom and centering. Addresses Issue #243.
=> Add Home Button

src/app/calendar/calendar.component.ts, src/app/week/week.component.ts
PSA: any variable used in a *.component.html file must be a public variable in corresponding *.component.ts files
=> Made private vars public for deployment

src/app/calendar/calendar.component.css, src/app/calendar/calendar.component.html, src/app/calendar/calendar.component.ts, src/app/event.service.ts, src/app/navbar/navbar.component.ts, src/app/week/week.component.ts
Fixed Calendar bugs
When you click a grey calendar cell it used to select the same number day in the current month. No more:
When you moved ahead 1 month, it would have the wrong events for each day, no more:
It also doesn't duplicate event descriptions in each calendar cell anymore:
Ok but I haven't fixed the filters yet, but that should be in a new branch.
=> Hakan calendar

src/app/date-selector/date-selector.component.ts, src/app/event.service.ts, src/app/map-box/map-box.component.ts, src/app/month/month.component.ts, src/app/navbar/navbar.component.ts, src/app/sidebar/sidebar.component.ts, src/app/week/week.component.ts
Sidebar activity and selected date are maintained when switching between map, week, and month view.
=> Proper Behavior when Switching Views

src/app/app.module.ts, src/app/calendar-container/calendar-container.component.ts, src/app/calendar.service.ts, src/app/category-bar-calendar/category-bar-calendar.component.ts, src/app/event.service.ts, src/app/map-box/map-box.component.ts, src/app/month/month.component.ts, src/app/navbar/navbar.component.html, src/app/navbar/navbar.component.ts, src/app/sidebar/sidebar.component.ts, src/app/week/week.component.ts
This branch fixes a number of small issues, including:
- Router issues are resolved, switching between map, week, and calendar view yields expected behavior
- Sidebar links to other views as expected, showing either an event card or the event list
- Map zooms out or to events on load or view switch
- Week view events are highlighted properly when selected
=> A few small functionality fixes

src/app/category-bar-calendar/category-bar-calendar.component.css, src/app/category-bar-calendar/category-bar-calendar.component.html
Olivia's Design:
What it looks like on my branch:
=> Filter Dropdown CSS Changes

src/app/calendar-container/calendar-container.component.css, src/app/calendar-container/calendar-container.component.ts, src/app/category-bar-calendar/category-bar-calendar.component.css, src/app/category-bar-calendar/category-bar-calendar.component.ts, src/app/category-bar-map/category-bar-map.component.css, src/app/category.service.ts, src/app/event-detail/event-detail.component.css, src/app/event.service.ts, src/app/month/month.component.ts, src/app/navbar/navbar.component.ts, src/app/week/week.component.css, src/app/week/week.component.ts
Filters will now:
- Initialize on correct values
- Reset when switching between map and calendar view
- Reset when incrementing day on map view
- Reset date filter when incrementing month, incrementing week, or switching between month and week
- Maintain all other filters when incrementing month, incrementing week, or switching between month and week (category, filter buttons, location, time)
=> Ryan Filters Correct on View Change

src/app/calendar.service.ts, src/app/category-bar-calendar/category-bar-calendar.component.css, src/app/category-bar-calendar/category-bar-calendar.component.html, src/app/category-bar-calendar/category-bar-calendar.component.ts, src/app/category.service.ts, src/app/event.service.ts, src/app/navbar/navbar.component.html
ryan did all the work, i just moved the clear all button:
=> Ryan filter cleanup

src/app/calendar-container/calendar-container.component.css, src/app/calendar-container/calendar-container.component.html, src/app/category-bar-calendar/category-bar-calendar.component.css, src/app/category-bar-calendar/category-bar-calendar.component.html, src/app/category-bar-calendar/category-bar-calendar.component.ts, src/app/date-selector/date-selector.component.css, src/app/date-selector/date-selector.component.html, src/app/event.service.ts, src/app/week/week.component.html, src/app/week/week.component.ts
- Fixed starting scroll time in week view
- Fixed caret positions for both date selector and calendar
- Converted calendar view category selector from dropdown to checkboxes
=> Misc changes

src/app/navbar/navbar.component.ts
Fixes the bugs in master that were preventing it from serving
=> Hakan fix master serve bugs

src/app/month/month.component.scss, src/app/services/event.service.ts, src/app/sidebar/sidebar.component.ts
Sidebar Events Now Display in Chronological Order:
Additionally, no events from previous days are shown (including those manually added):
=> Sidebar Events Chronological

README.md, angular.json, e2e/app.e2e-spec.ts, package.json, proxy.conf.json, src/app/app.component.ts, src/app/navbar/navbar.component.html, src/app/navbar/navbar.component.ts, src/assets/favicons/manifest.json, src/index.html, src/manifest.json, src/ngsw-config.json
Changed instances of Mappening to Bmaps
Fixed bug where "Calendar View" in not selected in week view
=> Athya's Frontend Fixes

proxy.conf.json, src/app/category-bar-calendar/category-bar-calendar.component.html, src/app/category-bar-calendar/category-bar-calendar.component.scss, src/app/category-bar-calendar/category-bar-calendar.component.ts
Fixed calendar filters!
Closes #316, closes #335
=> Amy calendar filters

Dockerfile, package.json, src/app/app.module.ts, src/app/navbar/navbar.component.html, src/app/navbar/navbar.component.scss, src/app/navbar/navbar.component.ts, src/index.html, src/main.ts, src/manifest.json, src/ngsw-config.json, yarn.lock
Convert our app into a PWA. Installable on desktop and mobile homescreen.
Fully tested on dev production site.
=> Progressive Web App
